plugins {
    id 'java'
}

group = 'sarinxo.edu'
version = '1.0-SNAPSHOT'



repositories {
    mavenCentral()
}

dependencies {
    implementation "org.projectlombok:lombok:${lombokVersion}"
    implementation "org.yaml:snakeyaml:${yamlVersion}"

    testImplementation "org.seleniumhq.selenium:selenium-java:${seleniumVersion}"
    testImplementation "org.seleniumhq.selenium:selenium-grid:${seleniumVersion}"
    testImplementation "com.titusfortner:selenium-logger:${seleniumLogger}"

    testImplementation platform("org.junit:junit-bom:${junitBomVersion}")
    testImplementation 'org.junit.jupiter:junit-jupiter-engine'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

}

test {
    useJUnitPlatform()
}