plugins {
    id 'java'
    id 'io.qameta.allure' version '2.11.2'
}

group = 'sarinxo.edu'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation "org.yaml:snakeyaml:${yamlVersion}"

    implementation "io.qameta.allure:allure-junit5:${allureVersion}"

    testCompileOnly "org.projectlombok:lombok:${lombokVersion}"
    testAnnotationProcessor "org.projectlombok:lombok:${lombokVersion}"

    testImplementation "org.seleniumhq.selenium:selenium-java:${seleniumVersion}"
    testImplementation "org.seleniumhq.selenium:selenium-grid:${seleniumVersion}"
    testImplementation "com.titusfortner:selenium-logger:${seleniumLogger}"

    testImplementation platform("org.junit:junit-bom:${junitBomVersion}")
    testImplementation 'org.junit.jupiter:junit-jupiter-engine'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

}

test {
    useJUnitPlatform()
}